---
# tasks file for nodejs
- name: Installing node and npm
  apt:
    name: "{{item}}"
  with_items:
    - nodejs
    - npm
- name: Installing pm2 using npm
  npm:
    name: "{{item}}"
    global: yes
  with_items:
    - pm2